// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STUDY.Blazor.FifaWorldCup.Server.Models;

#nullable disable

namespace STUDY.Blazor.FifaWorldCup.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("STUDY.Blazor.FifaWorldCup.Shared.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalsTeam1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsTeam2")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Seed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2022-05-05",
                            GoalsTeam1 = 1,
                            GoalsTeam2 = 0,
                            Seed = 'A',
                            Team1 = "Brazil",
                            Team2 = "Germany",
                            Venue = "King Stadium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
