// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STUDY.Blazor.FifaWorldCup.Server.Models;

#nullable disable

namespace STUDY.Blazor.FifaWorldCup.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("STUDY.Blazor.FifaWorldCup.Shared.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalsTeam1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsTeam2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Venue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2022-11-20 16:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 0,
                            Team1 = 1,
                            Team2 = 4,
                            Venue = 0
                        },
                        new
                        {
                            Id = 2,
                            Date = "2022-11-21 13:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 1,
                            Team1 = 5,
                            Team2 = 8,
                            Venue = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = "2022-11-21 16:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 0,
                            Team1 = 3,
                            Team2 = 2,
                            Venue = 2
                        },
                        new
                        {
                            Id = 4,
                            Date = "2022-11-21 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 1,
                            Team1 = 6,
                            Team2 = 7,
                            Venue = 3
                        },
                        new
                        {
                            Id = 5,
                            Date = "2022-11-22 10:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 2,
                            Team1 = 9,
                            Team2 = 12,
                            Venue = 4
                        },
                        new
                        {
                            Id = 6,
                            Date = "2022-11-22 13:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 3,
                            Team1 = 14,
                            Team2 = 15,
                            Venue = 5
                        },
                        new
                        {
                            Id = 7,
                            Date = "2022-11-22 16:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 2,
                            Team1 = 11,
                            Team2 = 10,
                            Venue = 6
                        },
                        new
                        {
                            Id = 8,
                            Date = "2022-11-22 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 3,
                            Team1 = 13,
                            Team2 = 16,
                            Venue = 7
                        },
                        new
                        {
                            Id = 9,
                            Date = "2022-11-23 10:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 5,
                            Team1 = 24,
                            Team2 = 22,
                            Venue = 0
                        },
                        new
                        {
                            Id = 10,
                            Date = "2022-11-23 13:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 4,
                            Team1 = 17,
                            Team2 = 19,
                            Venue = 1
                        },
                        new
                        {
                            Id = 11,
                            Date = "2022-11-23 16:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 4,
                            Team1 = 18,
                            Team2 = 20,
                            Venue = 2
                        },
                        new
                        {
                            Id = 12,
                            Date = "2022-11-23 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 5,
                            Team1 = 21,
                            Team2 = 23,
                            Venue = 3
                        },
                        new
                        {
                            Id = 13,
                            Date = "2022-11-23 10:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 6,
                            Team1 = 26,
                            Team2 = 28,
                            Venue = 7
                        },
                        new
                        {
                            Id = 14,
                            Date = "2022-11-24 13:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 7,
                            Team1 = 30,
                            Team2 = 32,
                            Venue = 5
                        },
                        new
                        {
                            Id = 15,
                            Date = "2022-11-24 16:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 7,
                            Team1 = 29,
                            Team2 = 31,
                            Venue = 6
                        },
                        new
                        {
                            Id = 16,
                            Date = "2022-11-23 13:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 6,
                            Team1 = 25,
                            Team2 = 27,
                            Venue = 1
                        },
                        new
                        {
                            Id = 17,
                            Date = "2022-11-25 10:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 1,
                            Team1 = 7,
                            Team2 = 8,
                            Venue = 3
                        },
                        new
                        {
                            Id = 18,
                            Date = "2022-11-25 13:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 0,
                            Team1 = 1,
                            Team2 = 3,
                            Venue = 2
                        },
                        new
                        {
                            Id = 19,
                            Date = "2022-11-25 16:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 0,
                            Team1 = 2,
                            Team2 = 4,
                            Venue = 1
                        },
                        new
                        {
                            Id = 20,
                            Date = "2022-11-25 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 1,
                            Team1 = 5,
                            Team2 = 6,
                            Venue = 1
                        },
                        new
                        {
                            Id = 21,
                            Date = "2022-11-26 10:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 3,
                            Team1 = 15,
                            Team2 = 16,
                            Venue = 7
                        },
                        new
                        {
                            Id = 22,
                            Date = "2022-11-26 13:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 2,
                            Team1 = 10,
                            Team2 = 12,
                            Venue = 5
                        },
                        new
                        {
                            Id = 23,
                            Date = "2022-11-26 16:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 3,
                            Team1 = 13,
                            Team2 = 14,
                            Venue = 6
                        },
                        new
                        {
                            Id = 24,
                            Date = "2022-11-26 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 2,
                            Team1 = 9,
                            Team2 = 11,
                            Venue = 4
                        },
                        new
                        {
                            Id = 25,
                            Date = "2022-11-27 10:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 4,
                            Team1 = 19,
                            Team2 = 20,
                            Venue = 3
                        },
                        new
                        {
                            Id = 26,
                            Date = "2022-11-27 13:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 5,
                            Team1 = 21,
                            Team2 = 24,
                            Venue = 2
                        },
                        new
                        {
                            Id = 27,
                            Date = "2022-11-27 16:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 5,
                            Team1 = 22,
                            Team2 = 23,
                            Venue = 1
                        },
                        new
                        {
                            Id = 28,
                            Date = "2022-11-27 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 4,
                            Team1 = 18,
                            Team2 = 17,
                            Venue = 0
                        },
                        new
                        {
                            Id = 29,
                            Date = "2022-11-28 10:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 6,
                            Team1 = 28,
                            Team2 = 27,
                            Venue = 7
                        },
                        new
                        {
                            Id = 30,
                            Date = "2022-11-28 13:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 7,
                            Team1 = 32,
                            Team2 = 31,
                            Venue = 5
                        },
                        new
                        {
                            Id = 31,
                            Date = "2022-11-28 16:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 6,
                            Team1 = 25,
                            Team2 = 26,
                            Venue = 6
                        },
                        new
                        {
                            Id = 32,
                            Date = "2022-11-28 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 7,
                            Team1 = 29,
                            Team2 = 30,
                            Venue = 4
                        },
                        new
                        {
                            Id = 33,
                            Date = "2022-11-29 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 0,
                            Team1 = 2,
                            Team2 = 1,
                            Venue = 1
                        },
                        new
                        {
                            Id = 34,
                            Date = "2022-11-29 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 0,
                            Team1 = 4,
                            Team2 = 3,
                            Venue = 0
                        },
                        new
                        {
                            Id = 35,
                            Date = "2022-11-29 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 1,
                            Team1 = 7,
                            Team2 = 5,
                            Venue = 3
                        },
                        new
                        {
                            Id = 36,
                            Date = "2022-11-29 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 1,
                            Team1 = 8,
                            Team2 = 6,
                            Venue = 2
                        },
                        new
                        {
                            Id = 37,
                            Date = "2022-11-30 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 3,
                            Team1 = 16,
                            Team2 = 14,
                            Venue = 7
                        },
                        new
                        {
                            Id = 38,
                            Date = "2022-11-30 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 3,
                            Team1 = 15,
                            Team2 = 13,
                            Venue = 5
                        },
                        new
                        {
                            Id = 39,
                            Date = "2022-11-30 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 2,
                            Team1 = 10,
                            Team2 = 9,
                            Venue = 6
                        },
                        new
                        {
                            Id = 40,
                            Date = "2022-11-30 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 2,
                            Team1 = 12,
                            Team2 = 11,
                            Venue = 4
                        },
                        new
                        {
                            Id = 41,
                            Date = "2022-12-01 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 5,
                            Team1 = 22,
                            Team2 = 21,
                            Venue = 3
                        },
                        new
                        {
                            Id = 42,
                            Date = "2022-12-01 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 5,
                            Team1 = 23,
                            Team2 = 24,
                            Venue = 2
                        },
                        new
                        {
                            Id = 43,
                            Date = "2022-12-01 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 4,
                            Team1 = 19,
                            Team2 = 18,
                            Venue = 1
                        },
                        new
                        {
                            Id = 44,
                            Date = "2022-12-01 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 4,
                            Team1 = 20,
                            Team2 = 17,
                            Venue = 0
                        },
                        new
                        {
                            Id = 45,
                            Date = "2022-12-02 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 7,
                            Team1 = 31,
                            Team2 = 30,
                            Venue = 7
                        },
                        new
                        {
                            Id = 46,
                            Date = "2022-12-02 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 7,
                            Team1 = 32,
                            Team2 = 29,
                            Venue = 5
                        },
                        new
                        {
                            Id = 47,
                            Date = "2022-12-02 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 6,
                            Team1 = 27,
                            Team2 = 26,
                            Venue = 6
                        },
                        new
                        {
                            Id = 48,
                            Date = "2022-12-02 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 6,
                            Team1 = 28,
                            Team2 = 25,
                            Venue = 4
                        },
                        new
                        {
                            Id = 49,
                            Date = "2022-12-03 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 1
                        },
                        new
                        {
                            Id = 50,
                            Date = "2022-12-03 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 3
                        },
                        new
                        {
                            Id = 51,
                            Date = "2022-12-04 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 2
                        },
                        new
                        {
                            Id = 52,
                            Date = "2022-12-04 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 0
                        },
                        new
                        {
                            Id = 53,
                            Date = "2022-12-05 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 7
                        },
                        new
                        {
                            Id = 54,
                            Date = "2022-12-05 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 6
                        },
                        new
                        {
                            Id = 55,
                            Date = "2022-12-06 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 5
                        },
                        new
                        {
                            Id = 56,
                            Date = "2022-12-06 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 4
                        },
                        new
                        {
                            Id = 57,
                            Date = "2022-12-09 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 5
                        },
                        new
                        {
                            Id = 58,
                            Date = "2022-12-09 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 4
                        },
                        new
                        {
                            Id = 59,
                            Date = "2022-12-10 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 0
                        },
                        new
                        {
                            Id = 60,
                            Date = "2022-12-10 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 2
                        },
                        new
                        {
                            Id = 61,
                            Date = "2022-12-13 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 4
                        },
                        new
                        {
                            Id = 62,
                            Date = "2022-12-14 19:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 0
                        },
                        new
                        {
                            Id = 63,
                            Date = "2022-12-17 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 1
                        },
                        new
                        {
                            Id = 64,
                            Date = "2022-12-18 15:00:00",
                            GoalsTeam1 = 0,
                            GoalsTeam2 = 0,
                            IsFinished = false,
                            Seed = 8,
                            Team1 = 0,
                            Team2 = 0,
                            Venue = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
